import { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './src/context/AuthContext';
const skinTypes = ['Normal', 'Seca', 'Oleosa', 'Mista', 'Sensível'];
export default function Cadastro() {
  const { signUp, isLoading } = useAuth(); const [nome, setNome] = useState(''); const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [confirmacaoSenha, setConfirmacaoSenha] = useState(''); const [tipoPele, setTipoPele] = useState('Normal');
  const submit = async () => { if (!nome.trim() || !email.trim() || senha.length < 6) return Alert.alert('Revise seus dados', 'Informe nome, e-mail e uma senha com pelo menos 6 caracteres.'); if (senha !== confirmacaoSenha) return Alert.alert('Senhas diferentes', 'Digite a mesma senha nos dois campos.'); try { await signUp(nome.trim(), email.trim().toLowerCase(), senha, tipoPele); router.replace('/'); } catch (error) { Alert.alert('Não foi possível criar a conta', error instanceof Error ? error.message : 'Tente novamente.'); } };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" size={19} color="#C74378"/><Text style={styles.backText}>Voltar</Text></Pressable><Text style={styles.eyebrow}>NOVA CONTA</Text><Text style={styles.title}>Comece com{`\n`}a sua pele.</Text><Text style={styles.subtitle}>Conte um pouco sobre você e vamos personalizar sua experiência.</Text><Text style={styles.label}>Nome</Text><TextInput style={styles.input} placeholder="Como quer ser chamada?" placeholderTextColor="#B29BA4" value={nome} onChangeText={setNome}/><Text style={styles.label}>E-mail</Text><TextInput style={styles.input} placeholder="voce@email.com" placeholderTextColor="#B29BA4" keyboardType="email-address" autoCapitalize="none" value={email} onChangeText={setEmail}/><Text style={styles.label}>Senha</Text><TextInput style={styles.input} placeholder="No mínimo 6 caracteres" placeholderTextColor="#B29BA4" secureTextEntry value={senha} onChangeText={setSenha}/><Text style={styles.label}>Confirmar senha</Text><TextInput style={styles.input} placeholder="Digite a senha novamente" placeholderTextColor="#B29BA4" secureTextEntry value={confirmacaoSenha} onChangeText={setConfirmacaoSenha}/><Text style={styles.label}>Como você define sua pele?</Text><View style={styles.chips}>{skinTypes.map(type => <Pressable key={type} style={[styles.chip, tipoPele === type && styles.selected]} onPress={() => setTipoPele(type)}><Text style={[styles.chipText, tipoPele === type && styles.selectedText]}>{type}</Text></Pressable>)}</View><Pressable style={[styles.button, isLoading && { opacity: .7 }]} onPress={submit} disabled={isLoading}>{isLoading ? <ActivityIndicator color="#fff"/> : <Text style={styles.buttonText}>Criar minha conta</Text>}</Pressable></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#fff' }, content: { padding: 24, paddingTop: 43, paddingBottom: 40 }, back: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 32 }, backText: { color: '#C74378', fontWeight: '800', fontSize: 13 }, eyebrow: { color: '#C74378', letterSpacing: 1.4, fontSize: 11, fontWeight: '800' }, title: { color: '#30252A', fontSize: 29, lineHeight: 34, fontWeight: '800', marginTop: 8 }, subtitle: { color: '#806671', lineHeight: 21, marginTop: 11, marginBottom: 30 }, label: { color: '#493740', fontSize: 13, fontWeight: '800', marginBottom: 5 }, input: { height: 49, borderBottomWidth: 1.2, borderBottomColor: '#EBDDE2', marginBottom: 20, color: '#30252A', fontSize: 15 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 7, marginBottom: 30 }, chip: { borderWidth: 1, borderColor: '#E8D9DE', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 9 }, selected: { backgroundColor: '#FCEBF1', borderColor: '#E8B5C7' }, chipText: { color: '#795F69', fontWeight: '700', fontSize: 13 }, selectedText: { color: '#B53669' }, button: { height: 53, backgroundColor: '#C74378', borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#fff', fontWeight: '800', fontSize: 16 } });
