import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './src/context/AuthContext';
import { useTheme } from './src/context/ThemeContext';
export default function Configuracao() {
  const { user, updatePreferences } = useAuth(); const { theme, isDark, toggleTheme } = useTheme();
  const changeNotifications = (value: boolean) => { if (!user) { router.push('/login' as any); return; } updatePreferences({ notificacoes: value }).catch(() => undefined); };
  return <View style={[styles.screen, { backgroundColor: theme.background }]}><Text style={[styles.eyebrow, { color: theme.primary }]}>PREFERÊNCIAS</Text><Text style={[styles.title, { color: theme.text }]}>Configurações</Text><Pressable style={[styles.account, { backgroundColor: theme.surface, borderColor: theme.border }]} onPress={() => router.push((user ? '/perfil' : '/login') as any)}><View style={[styles.accountIcon, { backgroundColor: theme.accentSoft }]}><Ionicons name="person-outline" size={20} color={theme.primary}/></View><View style={{ flex: 1 }}><Text style={[styles.accountName, { color: theme.text }]}>{user?.nome || 'Acesse sua conta'}</Text><Text style={[styles.accountEmail, { color: theme.textMuted }]}>{user?.email || 'Salve suas preferências'}</Text></View><Ionicons name="chevron-forward" size={20} color={theme.textMuted}/></Pressable><Text style={[styles.section, { color: theme.textMuted }]}>EXPERIÊNCIA</Text><View style={[styles.settings, { borderTopColor: theme.border }]}><Setting icon="notifications-outline" label="Notificações" value={user?.notificacoes ?? false} onChange={changeNotifications} theme={theme}/><Setting icon="moon-outline" label="Modo escuro" value={isDark} onChange={toggleTheme} theme={theme}/><Pressable style={[styles.row, { borderBottomColor: theme.border }]} onPress={() => router.push('/sobre' as any)}><View style={[styles.rowIcon, { backgroundColor: theme.accentSoft }]}><Ionicons name="information-circle-outline" size={19} color={theme.primary}/></View><Text style={[styles.rowText, { color: theme.text }]}>Sobre o Divas</Text><Ionicons name="chevron-forward" size={19} color={theme.textMuted}/></Pressable></View><Text style={[styles.footer, { color: theme.textMuted }]}>DIVAS · VERSÃO 1.0.0</Text></View>;
}
function Setting({ icon, label, value, onChange, theme }: { icon: string; label: string; value: boolean; onChange: (value: boolean) => void; theme: { primary: string; text: string; border: string; accentSoft: string } }) { return <View style={[styles.row, { borderBottomColor: theme.border }]}><View style={[styles.rowIcon, { backgroundColor: theme.accentSoft }]}><Ionicons name={icon as any} size={19} color={theme.primary}/></View><Text style={[styles.rowText, { color: theme.text }]}>{label}</Text><Switch value={value} onValueChange={onChange} trackColor={{ false: '#E7DDE1', true: '#E9A9C1' }} thumbColor={value ? theme.primary : '#fff'}/></View> }
const styles = StyleSheet.create({ screen: { flex: 1, padding: 22 }, eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: '800', marginTop: 5 }, title: { fontSize: 28, fontWeight: '800', marginTop: 7 }, account: { marginTop: 28, borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, accountIcon: { width: 41, height: 41, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, accountName: { fontWeight: '800', fontSize: 15 }, accountEmail: { fontSize: 12, marginTop: 4 }, section: { marginTop: 31, marginBottom: 10, fontSize: 11, fontWeight: '800', letterSpacing: 1.3 }, settings: { borderTopWidth: 1 }, row: { height: 67, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 12 }, rowIcon: { width: 35, height: 35, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, rowText: { flex: 1, fontWeight: '700', fontSize: 15 }, footer: { fontSize: 10, letterSpacing: 1, textAlign: 'center', marginTop: 36, fontWeight: '700' } });
