import { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './src/context/AuthContext';

export default function Login() {
  const { signIn, isLoading } = useAuth(); const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [visible, setVisible] = useState(false);
  const submit = async () => { if (!email.trim() || !senha) return Alert.alert('Faltam dados', 'Informe seu e-mail e sua senha.'); try { await signIn(email.trim().toLowerCase(), senha); router.replace('/'); } catch (error) { Alert.alert('Não foi possível entrar', error instanceof Error ? error.message : 'Tente novamente.'); } };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Pressable style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" color="#C74378" size={20}/><Text style={styles.backText}>Voltar</Text></Pressable><View style={styles.mark}><Text style={styles.markText}>D</Text></View><Text style={styles.brand}>divas</Text></View><View style={styles.content}><Text style={styles.title}>Bem-vinda de volta</Text><Text style={styles.subtitle}>Entre para continuar sua rotina de autocuidado.</Text><Text style={styles.label}>E-mail</Text><TextInput style={styles.input} placeholder="voce@email.com" placeholderTextColor="#B29BA4" keyboardType="email-address" autoCapitalize="none" value={email} onChangeText={setEmail}/><Text style={styles.label}>Senha</Text><View style={styles.password}><TextInput style={styles.passwordInput} placeholder="Sua senha" placeholderTextColor="#B29BA4" secureTextEntry={!visible} value={senha} onChangeText={setSenha}/><Pressable hitSlop={10} onPress={() => setVisible(!visible)}><Ionicons name={visible ? 'eye-off-outline' : 'eye-outline'} color="#937681" size={20}/></Pressable></View><Pressable style={[styles.button, isLoading && { opacity: .7 }]} disabled={isLoading} onPress={submit}>{isLoading ? <ActivityIndicator color="#fff"/> : <Text style={styles.buttonText}>Entrar</Text>}</Pressable><Pressable style={styles.newAccount} onPress={() => router.push('/cadastro' as any)}><Text style={styles.newText}>Ainda não tem conta? <Text style={styles.pink}>Criar conta</Text></Text></Pressable></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#fff' }, header: { backgroundColor: '#FCEBF1', paddingTop: 55, paddingBottom: 33, alignItems: 'center' }, back: { position: 'absolute', left: 22, top: 57, flexDirection: 'row', gap: 6, alignItems: 'center' }, backText: { color: '#C74378', fontWeight: '800', fontSize: 13 }, mark: { width: 50, height: 50, borderRadius: 17, backgroundColor: '#C74378', alignItems: 'center', justifyContent: 'center' }, markText: { color: '#fff', fontSize: 28, fontWeight: '800' }, brand: { color: '#30252A', fontSize: 24, fontWeight: '800', marginTop: 8 }, content: { flex: 1, padding: 25, paddingTop: 35 }, title: { color: '#30252A', fontWeight: '800', fontSize: 27 }, subtitle: { color: '#806671', marginTop: 8, lineHeight: 21, marginBottom: 32 }, label: { color: '#493740', fontSize: 13, fontWeight: '800', marginBottom: 8 }, input: { height: 53, borderBottomWidth: 1.2, borderBottomColor: '#EBDDE2', color: '#30252A', fontSize: 16, marginBottom: 24 }, password: { height: 53, borderBottomWidth: 1.2, borderBottomColor: '#EBDDE2', flexDirection: 'row', alignItems: 'center', marginBottom: 32 }, passwordInput: { flex: 1, color: '#30252A', fontSize: 16 }, button: { height: 53, borderRadius: 14, backgroundColor: '#C74378', alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#fff', fontSize: 16, fontWeight: '800' }, newAccount: { alignItems: 'center', padding: 23 }, newText: { color: '#806671', fontSize: 13 }, pink: { color: '#C74378', fontWeight: '800' } });
