import { useEffect } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from './src/context/AuthContext';
export default function Perfil() {
  const { user, signOut } = useAuth();
  useEffect(() => {
    if (!user) router.replace('/login' as any);
  }, [user]);
  if (!user) return null;
  const leave = () => Alert.alert('Sair da conta', 'Você poderá entrar novamente a qualquer momento.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Sair', style: 'destructive', onPress: () => { signOut(); router.replace('/login' as any); } }]);
  const rows = [{ icon: 'color-wand-outline', text: 'Meu diagnóstico', route: '/quiz' }, { icon: 'heart-outline', text: 'Produtos favoritos', route: '/produtos' }, { icon: 'settings-outline', text: 'Configurações', route: '/configuracao' }];
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>MEU ESPAÇO</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.initial}>{user.nome.charAt(0).toUpperCase()}</Text></View><View><Text style={styles.name}>{user.nome}</Text><Text style={styles.email}>{user.email}</Text></View></View><View style={styles.skin}><View style={styles.skinIcon}><Ionicons name="sparkles-outline" size={21} color="#C74378"/></View><View><Text style={styles.skinLabel}>SEU PERFIL DE PELE</Text><Text style={styles.skinTitle}>Pele {user.tipo_pele || 'não informada'}</Text></View><Pressable onPress={() => router.push('/quiz')}><Ionicons name="chevron-forward" size={20} color="#B698A3"/></Pressable></View><Text style={styles.section}>CONTA</Text><View style={styles.list}>{rows.map(row => <Pressable key={row.text} style={styles.row} onPress={() => router.push(row.route as any)}><Ionicons name={row.icon as any} size={20} color="#C74378"/><Text style={styles.rowText}>{row.text}</Text><Ionicons name="chevron-forward" size={19} color="#B698A3"/></Pressable>)}</View><Pressable style={styles.logout} onPress={leave}><Ionicons name="log-out-outline" size={19} color="#B53B62"/><Text style={styles.logoutText}>Sair da conta</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#fff' }, content: { padding: 22 }, eyebrow: { color: '#C74378', fontSize: 11, fontWeight: '800', letterSpacing: 1.4, marginTop: 5, marginBottom: 20 }, profile: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 26 }, avatar: { width: 62, height: 62, borderRadius: 21, backgroundColor: '#F8E1EA', alignItems: 'center', justifyContent: 'center' }, initial: { color: '#B53669', fontSize: 27, fontWeight: '800' }, name: { color: '#30252A', fontSize: 21, fontWeight: '800' }, email: { color: '#896F79', marginTop: 4, fontSize: 13 }, skin: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#FDF1F5', borderRadius: 18, padding: 16 }, skinIcon: { width: 39, height: 39, backgroundColor: '#fff', borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, skinLabel: { color: '#A57888', fontSize: 10, fontWeight: '800', letterSpacing: .6 }, skinTitle: { color: '#47323B', fontSize: 15, fontWeight: '800', marginTop: 3, flex: 1 }, section: { color: '#A17F8B', fontWeight: '800', letterSpacing: 1.3, fontSize: 11, marginTop: 30, marginBottom: 10 }, list: { borderTopWidth: 1, borderTopColor: '#F1E8EB' }, row: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1, borderBottomColor: '#F1E8EB' }, rowText: { flex: 1, color: '#47323B', fontWeight: '700', fontSize: 15 }, logout: { marginTop: 25, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 9 }, logoutText: { color: '#B53B62', fontWeight: '800', fontSize: 14 } });
