import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
const categories = [
  { title: 'Maquiagem', description: 'Realce a sua expressão', icon: 'color-palette-outline', route: './categorias/Maquiagem/maquiagem', color: '#FCEAF1' },
  { title: 'Cabelos', description: 'Cuidado para todos os fios', icon: 'leaf-outline', route: './categorias/Cabelo/cabelo', color: '#FDF0F4' },
  { title: 'Pele', description: 'Sua rotina facial essencial', icon: 'water-outline', route: './categorias/Pele/pele', color: '#FCEBF1' },
  { title: 'Rosto', description: 'Detalhes que fazem diferença', icon: 'sparkles-outline', route: './categorias/Rosto/rosto', color: '#FFF4F7' },
];
export default function Produtos() { return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ENCONTRE O QUE PRECISA</Text><Text style={styles.title}>Categorias</Text><Text style={styles.subtitle}>Escolha uma categoria para explorar produtos e montar sua rotina.</Text><View style={styles.grid}>{categories.map(item => <Pressable key={item.title} style={styles.card} onPress={() => router.push(item.route as any)}><View style={[styles.icon, { backgroundColor: item.color }]}><Ionicons name={item.icon as any} size={27} color="#C74378"/></View><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardDescription}>{item.description}</Text><View style={styles.arrow}><Ionicons name="arrow-forward" size={16} color="#C74378"/></View></Pressable>)}</View></ScrollView> }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#fff' }, content: { padding: 22, paddingTop: 26, paddingBottom: 42 }, eyebrow: { color: '#C74378', fontSize: 11, letterSpacing: 1.4, fontWeight: '800' }, title: { color: '#30252A', fontSize: 29, fontWeight: '800', marginTop: 8 }, subtitle: { color: '#806671', lineHeight: 21, marginTop: 8, marginBottom: 26, maxWidth: 315 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 13 }, card: { width: '47.8%', minHeight: 184, borderWidth: 1, borderColor: '#F0E6E9', borderRadius: 20, padding: 15 }, icon: { width: 49, height: 49, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: 20 }, cardTitle: { color: '#35272D', fontSize: 16, fontWeight: '800' }, cardDescription: { color: '#927782', fontSize: 12, lineHeight: 17, marginTop: 5 }, arrow: { marginTop: 'auto', width: 29, height: 29, borderRadius: 10, backgroundColor: '#FCEBF1', alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-end' } });
