import { useRef, useState } from 'react';
import { Animated, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useTheme } from './src/context/ThemeContext';
import { useAuth } from './src/context/AuthContext';
import { supabase } from '../lib/supabase';

type Skin = 'oleosa' | 'seca' | 'sensivel';
const questions: { title: string; subtitle: string; answers: { text: string; type: Skin; icon: string }[] }[] = [
  { title: 'Como sua pele fica ao final do dia?', subtitle: 'Escolha a alternativa que mais parece com você.', answers: [{ text: 'Com bastante brilho', type: 'oleosa', icon: 'sunny-outline' }, { text: 'Repuxando ou ressecada', type: 'seca', icon: 'water-outline' }, { text: 'Irritada com facilidade', type: 'sensivel', icon: 'leaf-outline' }] },
  { title: 'Como você percebe seus poros?', subtitle: 'Observe principalmente a região T do rosto.', answers: [{ text: 'Mais aparentes', type: 'oleosa', icon: 'scan-outline' }, { text: 'Pouco visíveis', type: 'seca', icon: 'ellipse-outline' }, { text: 'Variam ou incomodam', type: 'sensivel', icon: 'pulse-outline' }] },
  { title: 'Com que frequência sua pele fica vermelha?', subtitle: 'Pense na sua rotina nas últimas semanas.', answers: [{ text: 'Frequentemente', type: 'sensivel', icon: 'flame-outline' }, { text: 'Raramente', type: 'oleosa', icon: 'checkmark-circle-outline' }, { text: 'Às vezes', type: 'seca', icon: 'partly-sunny-outline' }] },
];

const results = { oleosa: { icon: 'sunny-outline', title: 'Pele oleosa', text: 'Prefira limpeza em gel, hidratante oil-free e protetor solar com toque seco.' }, seca: { icon: 'water-outline', title: 'Pele seca', text: 'Invista em limpeza suave, ácido hialurônico e hidratação mais intensa.' }, sensivel: { icon: 'leaf-outline', title: 'Pele sensível', text: 'Busque fórmulas suaves, sem álcool e com ativos calmantes.' }, normal: { icon: 'sparkles-outline', title: 'Pele equilibrada', text: 'Mantenha uma rotina simples: limpeza, hidratação e proteção solar diária.' } };

export default function Quiz() {
  const { theme } = useTheme();
  const { user } = useAuth();
  const [step, setStep] = useState(0); const [scores, setScores] = useState<Record<Skin, number>>({ oleosa: 0, seca: 0, sensivel: 0 }); const [selected, setSelected] = useState<string | null>(null); const [finished, setFinished] = useState(false);
  const opacity = useRef(new Animated.Value(1)).current; const translate = useRef(new Animated.Value(0)).current;
  const animate = (next: () => void) => Animated.parallel([Animated.timing(opacity, { toValue: 0, duration: 150, useNativeDriver: true }), Animated.timing(translate, { toValue: -12, duration: 150, useNativeDriver: true })]).start(() => { next(); translate.setValue(12); Animated.parallel([Animated.timing(opacity, { toValue: 1, duration: 230, useNativeDriver: true }), Animated.spring(translate, { toValue: 0, useNativeDriver: true, friction: 8 })]).start(); });
  const saveResult = async (nextScores: Record<Skin, number>) => { if (!user) return; const bestResult = (Object.entries(nextScores).sort((a, b) => b[1] - a[1])[0]?.[0] || 'normal') as keyof typeof results; const skinType = { oleosa: 'Oleosa', seca: 'Seca', sensivel: 'Sensível', normal: 'Normal' }[bestResult]; await supabase.from('quiz_results').insert({ user_id: user.id, result_type: bestResult, scores: nextScores }); await supabase.from('profiles').update({ skin_type: skinType }).eq('id', user.id); };
  const answer = (type: Skin, text: string) => { if (selected) return; setSelected(text); const nextScores = { ...scores, [type]: scores[type] + 1 }; setScores(nextScores); setTimeout(() => animate(() => { setSelected(null); if (step === questions.length - 1) { setFinished(true); saveResult(nextScores).catch(() => undefined); } else setStep(step + 1); }), 180); };
  const restart = () => { setStep(0); setScores({ oleosa: 0, seca: 0, sensivel: 0 }); setSelected(null); animate(() => setFinished(false)); };
  const best = (Object.entries(scores).sort((a, b) => b[1] - a[1])[0]?.[0] || 'normal') as keyof typeof results;
  const question = questions[step]; const progress = finished ? 1 : (step + 1) / questions.length;
  return <View style={[styles.screen, { backgroundColor: theme.background }]}><View style={styles.top}><Text style={[styles.eyebrow, { color: theme.primary }]}>DIAGNÓSTICO DE PELE</Text><Text style={[styles.counter, { color: theme.textMuted }]}>{finished ? 'Concluído' : `${step + 1} de ${questions.length}`}</Text></View><View style={[styles.track, { backgroundColor: theme.border }]}><View style={[styles.progress, { backgroundColor: theme.primary, width: `${progress * 100}%` }]}/></View><Animated.View style={[styles.body, { opacity, transform: [{ translateX: translate }] }]}>{finished ? <Result result={results[best]} onRestart={restart} theme={theme} /> : <><View style={[styles.questionIcon, { backgroundColor: theme.accentSoft }]}><Ionicons name="sparkles-outline" size={27} color={theme.primary}/></View><Text style={[styles.title, { color: theme.text }]}>{question.title}</Text><Text style={[styles.subtitle, { color: theme.textMuted }]}>{question.subtitle}</Text><View style={styles.answers}>{question.answers.map((item, index) => <Pressable key={item.text} onPress={() => answer(item.type, item.text)} style={[styles.answer, { backgroundColor: theme.surface, borderColor: selected === item.text ? theme.primary : theme.border }, selected === item.text && { backgroundColor: theme.accentSoft }]}><View style={[styles.number, { backgroundColor: theme.accentSoft }]}><Text style={[styles.numberText, { color: theme.primary }]}>{index + 1}</Text></View><Ionicons name={item.icon as any} size={21} color={theme.primary}/><Text style={[styles.answerText, { color: theme.text }]}>{item.text}</Text><Ionicons name={selected === item.text ? 'checkmark-circle' : 'chevron-forward'} size={20} color={selected === item.text ? theme.primary : theme.textMuted}/></Pressable>)}</View></>}</Animated.View></View>;
}
function Result({ result, onRestart, theme }: { result: typeof results[keyof typeof results]; onRestart: () => void; theme: { accentSoft: string; primary: string; text: string; textMuted: string } }) { return <View style={styles.result}><View style={[styles.resultIcon, { backgroundColor: theme.accentSoft }]}><Ionicons name={result.icon as any} size={36} color={theme.primary}/></View><Text style={[styles.resultOverline, { color: theme.primary }]}>SUA PELE É</Text><Text style={[styles.resultTitle, { color: theme.text }]}>{result.title}</Text><Text style={[styles.resultText, { color: theme.textMuted }]}>{result.text}</Text><Pressable style={[styles.primary, { backgroundColor: theme.primary }]} onPress={() => router.push('/produtos')}><Text style={styles.primaryText}>Ver produtos indicados</Text><Ionicons name="arrow-forward" size={18} color="#fff"/></Pressable><Pressable style={styles.restart} onPress={onRestart}><Text style={[styles.restartText, { color: theme.primary }]}>Refazer diagnóstico</Text></Pressable></View> }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#fff', padding: 22 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 }, eyebrow: { color: '#C74378', fontSize: 11, letterSpacing: 1.2, fontWeight: '800' }, counter: { color: '#927680', fontWeight: '700', fontSize: 12 }, track: { height: 5, backgroundColor: '#F2E8EB', borderRadius: 4, marginTop: 16 }, progress: { height: 5, backgroundColor: '#C74378', borderRadius: 4 }, body: { flex: 1, justifyContent: 'center', paddingBottom: 48 }, questionIcon: { width: 58, height: 58, borderRadius: 19, backgroundColor: '#FCEBF1', alignItems: 'center', justifyContent: 'center', marginBottom: 23 }, title: { color: '#30252A', fontSize: 27, lineHeight: 33, fontWeight: '800', maxWidth: 330 }, subtitle: { color: '#816872', fontSize: 15, lineHeight: 22, marginTop: 11, marginBottom: 30 }, answers: { gap: 11 }, answer: { minHeight: 66, borderWidth: 1, borderColor: '#EFE5E8', borderRadius: 17, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, answerSelected: { borderColor: '#E6A8BF', backgroundColor: '#FFF7F9' }, number: { width: 23, height: 23, borderRadius: 12, backgroundColor: '#FCEBF1', alignItems: 'center', justifyContent: 'center' }, numberText: { color: '#B83A6A', fontSize: 11, fontWeight: '800' }, answerText: { color: '#4B3841', flex: 1, fontWeight: '700', fontSize: 14 }, result: { alignItems: 'center' }, resultIcon: { width: 78, height: 78, borderRadius: 26, backgroundColor: '#FCEBF1', alignItems: 'center', justifyContent: 'center', marginBottom: 25 }, resultOverline: { color: '#C74378', fontSize: 11, letterSpacing: 1.3, fontWeight: '800' }, resultTitle: { color: '#30252A', fontSize: 29, fontWeight: '800', marginTop: 6 }, resultText: { color: '#806671', textAlign: 'center', lineHeight: 23, marginTop: 16, maxWidth: 310 }, primary: { marginTop: 30, height: 52, paddingHorizontal: 20, borderRadius: 14, backgroundColor: '#C74378', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }, primaryText: { color: '#fff', fontWeight: '800' }, restart: { padding: 18 }, restartText: { color: '#B5396A', fontWeight: '800', fontSize: 13 } });
